### ISSUE TITLE
[bug] whitespace gets introduced within <text>

### ISSUE THREAD

**Issue by tobwen** [benboba/svg-slim#30]
## summary
In https://github.com/benboba/svg-slim/commit/454349f2414c168fa8941bbcd80688c973d2fa29, some whitespace gets introduced within _text_-tag.

## incoming SVG
```svg
<svg xmlns="http://www.w3.org/2000/svg" version="1.0" width="1000" height="150">
  <text font-size="20px" x="500" y="100">
      <tspan>fixme</tspan>
  </text>
</svg>
```

## after processing with _svg-slim_
```svg
<svg xmlns="http://www.w3.org/2000/svg" width="1e3" height="150"><text font-size="20" x="5e2" y="1e2"> fixme </text></svg>
```

**Comment by benboba** [comment]
This is not a bug, blank characters in the text element will also be rendered, so you cannot trim both sides of the text directly
