### ISSUE TITLE
[feature request] keep unit for font-size

### ISSUE THREAD

**Issue by tobwen** [benboba/svg-slim#31]
## summary
Some browsers, like _Internet Explorer 11_, need a unit at font-size. Seems like config `browsers: []` is perfect for this in the future.

## incoming SVG
```svg
<svg xmlns="http://www.w3.org/2000/svg" version="1.0" width="1000" height="150">
  <text font-size="20px" x="500" y="100">
      <tspan>fixme</tspan>
  </text>
</svg>
```

## after processing with _svg-slim_
```svg
<svg xmlns="http://www.w3.org/2000/svg" width="1e3" height="150"><text font-size="20" x="5e2" y="1e2"> fixme </text></svg>
```

## should be for _IE11_
```svg
<svg xmlns="http://www.w3.org/2000/svg" width="1e3" height="150"><text font-size="20px" x="5e2" y="1e2">fixme</text></svg>
```

**Comment by benboba** [comment]
After verification, it is not just a problem of ie11. Some styles can omit the px unit when used as attributes, and they cannot be omitted in the style attribute and style tag. I will deal with this problem in a unified manner and release it together in 2.0.1

Currently known properties are: font-size, letter-spacing, word-spacing
