### ISSUE TITLE
[feature request] merge styles of nested TSPANs

### ISSUE THREAD

**Issue by tobwen** [benboba/svg-slim#32]
## summary
As discussed in https://github.com/benboba/svg-slim/issues/27, sometimes an SVG can contain nested _TSPAN_-elements. That's bad of course. But perhaps we can fix this. As you can see, the styled of the inner TSPAN gets lost. It contains `fill: red` aka `fill: #FF0000;`, which gets lost right now. Also, the `x` and `y` coordinates of the surrounding TSPAN gets lost (this is fine in this case since they're zero).

It should be discussed, what to do in such cases. I think the lower solution might be fine?

## incoming SVG
```svg
<svg xmlns="http://www.w3.org/2000/svg" version="1.0" width="900" height="150">
  <text x="500.298343" y="115.726494" style="fill:#00FF00;">
     <tspan x="0.000" y="0.000">
       <tspan style="fill:#FF0000;">fixme</tspan>
     </tspan>
  </text>
</svg>
```

## incoming processed SVG
```svg
<svg xmlns="http://www.w3.org/2000/svg" width="9e2" height="150">
  <text x="500.29834" y="115.72649" fill="#0f0">
    <tspan>fixme</tspan>
  </text>
</svg>
```

## one solution
```svg
<svg xmlns="http://www.w3.org/2000/svg" width="9e2" height="150">
  <text x="500.29834" y="115.72649" fill="#0f0">
    <tspan fill="red" x="0" y="0">fixme</tspan>
  </text>
</svg>
```

**Comment by benboba** [comment]
This problem has been fixed in v1.0.8, and now tspan nesting is no longer considered illegal nesting, but when the child element of tspan has only another tspan, it will be collapsed and all attributes will be merged
