### ISSUE TITLE
[feature request] donation

### ISSUE THREAD

**Issue by tobwen** [benboba/svg-slim#33]
Is it possible to donate you and your development?

**Comment by benboba** [comment]
Thank you for your support. I haven’t joined the github sponsorship program yet. I’ll apply for it now and I will update it in the document later

**Comment by benboba** [comment]
I'm in China, it seems that GitHubSponsors is not supported temporarily

**Comment by tobwen** [comment]
Hmm... Is Bitcoin or Paypal allowed in China?

**Comment by benboba** [comment]
Yes, I have a paypal account: https://paypal.me/benboba

**Comment by tobwen** [comment]
Done.
